/*
 * API de Energy and Water
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.57
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from './ApiClient';
import CategoriaServicioIdBody from './model/CategoriaServicioIdBody';
import CategoriaServicioIdBody1 from './model/CategoriaServicioIdBody1';
import EquipoIdBody from './model/EquipoIdBody';
import EquipoIdBody1 from './model/EquipoIdBody1';
import HistoriaIdBody from './model/HistoriaIdBody';
import HistoriaIdBody1 from './model/HistoriaIdBody1';
import InfoContactoIdBody from './model/InfoContactoIdBody';
import InfoContactoIdBody1 from './model/InfoContactoIdBody1';
import MantenimientoInfoIdBody from './model/MantenimientoInfoIdBody';
import MantenimientoInfoIdBody1 from './model/MantenimientoInfoIdBody1';
import PreguntaFrecuenteIdBody from './model/PreguntaFrecuenteIdBody';
import PreguntaFrecuenteIdBody1 from './model/PreguntaFrecuenteIdBody1';
import V1CategoriaServicioBody from './model/V1CategoriaServicioBody';
import V1EquipoBody from './model/V1EquipoBody';
import V1HistoriaBody from './model/V1HistoriaBody';
import V1InfoContactoBody from './model/V1InfoContactoBody';
import V1MantenimientoInfoBody from './model/V1MantenimientoInfoBody';
import V1PreguntaFrecuenteBody from './model/V1PreguntaFrecuenteBody';
import V1equipoidImagenes from './model/V1equipoidImagenes';
import V1equipoidImagenes1 from './model/V1equipoidImagenes1';
import DefaultApi from './api/DefaultApi';

/**
* Object.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var ApiDeEnergyAndWater = require('index'); // See note below*.
* var xxxSvc = new ApiDeEnergyAndWater.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new ApiDeEnergyAndWater.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new ApiDeEnergyAndWater.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new ApiDeEnergyAndWater.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The CategoriaServicioIdBody model constructor.
     * @property {module:model/CategoriaServicioIdBody}
     */
    CategoriaServicioIdBody,

    /**
     * The CategoriaServicioIdBody1 model constructor.
     * @property {module:model/CategoriaServicioIdBody1}
     */
    CategoriaServicioIdBody1,

    /**
     * The EquipoIdBody model constructor.
     * @property {module:model/EquipoIdBody}
     */
    EquipoIdBody,

    /**
     * The EquipoIdBody1 model constructor.
     * @property {module:model/EquipoIdBody1}
     */
    EquipoIdBody1,

    /**
     * The HistoriaIdBody model constructor.
     * @property {module:model/HistoriaIdBody}
     */
    HistoriaIdBody,

    /**
     * The HistoriaIdBody1 model constructor.
     * @property {module:model/HistoriaIdBody1}
     */
    HistoriaIdBody1,

    /**
     * The InfoContactoIdBody model constructor.
     * @property {module:model/InfoContactoIdBody}
     */
    InfoContactoIdBody,

    /**
     * The InfoContactoIdBody1 model constructor.
     * @property {module:model/InfoContactoIdBody1}
     */
    InfoContactoIdBody1,

    /**
     * The MantenimientoInfoIdBody model constructor.
     * @property {module:model/MantenimientoInfoIdBody}
     */
    MantenimientoInfoIdBody,

    /**
     * The MantenimientoInfoIdBody1 model constructor.
     * @property {module:model/MantenimientoInfoIdBody1}
     */
    MantenimientoInfoIdBody1,

    /**
     * The PreguntaFrecuenteIdBody model constructor.
     * @property {module:model/PreguntaFrecuenteIdBody}
     */
    PreguntaFrecuenteIdBody,

    /**
     * The PreguntaFrecuenteIdBody1 model constructor.
     * @property {module:model/PreguntaFrecuenteIdBody1}
     */
    PreguntaFrecuenteIdBody1,

    /**
     * The V1CategoriaServicioBody model constructor.
     * @property {module:model/V1CategoriaServicioBody}
     */
    V1CategoriaServicioBody,

    /**
     * The V1EquipoBody model constructor.
     * @property {module:model/V1EquipoBody}
     */
    V1EquipoBody,

    /**
     * The V1HistoriaBody model constructor.
     * @property {module:model/V1HistoriaBody}
     */
    V1HistoriaBody,

    /**
     * The V1InfoContactoBody model constructor.
     * @property {module:model/V1InfoContactoBody}
     */
    V1InfoContactoBody,

    /**
     * The V1MantenimientoInfoBody model constructor.
     * @property {module:model/V1MantenimientoInfoBody}
     */
    V1MantenimientoInfoBody,

    /**
     * The V1PreguntaFrecuenteBody model constructor.
     * @property {module:model/V1PreguntaFrecuenteBody}
     */
    V1PreguntaFrecuenteBody,

    /**
     * The V1equipoidImagenes model constructor.
     * @property {module:model/V1equipoidImagenes}
     */
    V1equipoidImagenes,

    /**
     * The V1equipoidImagenes1 model constructor.
     * @property {module:model/V1equipoidImagenes1}
     */
    V1equipoidImagenes1,

    /**
    * The DefaultApi service constructor.
    * @property {module:api/DefaultApi}
    */
    DefaultApi
};
