/*
 * API de Energy and Water
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.57
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import V1equipoidImagenes1 from './V1equipoidImagenes1';

/**
 * The EquipoIdBody1 model module.
 * @module model/EquipoIdBody1
 * @version 1.0.0
 */
export default class EquipoIdBody1 {
  /**
   * Constructs a new <code>EquipoIdBody1</code>.
   * @alias module:model/EquipoIdBody1
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>EquipoIdBody1</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/EquipoIdBody1} obj Optional instance to populate.
   * @return {module:model/EquipoIdBody1} The populated <code>EquipoIdBody1</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new EquipoIdBody1();
      if (data.hasOwnProperty('tipo'))
        obj.tipo = ApiClient.convertToType(data['tipo'], 'String');
      if (data.hasOwnProperty('texto'))
        obj.texto = ApiClient.convertToType(data['texto'], 'String');
      if (data.hasOwnProperty('activo'))
        obj.activo = ApiClient.convertToType(data['activo'], 'Boolean');
      if (data.hasOwnProperty('imagenes'))
        obj.imagenes = ApiClient.convertToType(data['imagenes'], [V1equipoidImagenes1]);
    }
    return obj;
  }
}

/**
 * @member {String} tipo
 */
EquipoIdBody1.prototype.tipo = undefined;

/**
 * @member {String} texto
 */
EquipoIdBody1.prototype.texto = undefined;

/**
 * @member {Boolean} activo
 */
EquipoIdBody1.prototype.activo = undefined;

/**
 * @member {Array.<module:model/V1equipoidImagenes1>} imagenes
 */
EquipoIdBody1.prototype.imagenes = undefined;

