/*
 * API de Energy and Water
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.57
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import V1equipoidImagenes from './V1equipoidImagenes';

/**
 * The V1EquipoBody model module.
 * @module model/V1EquipoBody
 * @version 1.0.0
 */
export default class V1EquipoBody {
  /**
   * Constructs a new <code>V1EquipoBody</code>.
   * @alias module:model/V1EquipoBody
   * @class
   * @param tipo {String} 
   * @param texto {String} 
   * @param activo {Boolean} 
   * @param imagenes {Array.<module:model/V1equipoidImagenes>} 
   */
  constructor(tipo, texto, activo, imagenes) {
    this.tipo = tipo;
    this.texto = texto;
    this.activo = activo;
    this.imagenes = imagenes;
  }

  /**
   * Constructs a <code>V1EquipoBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/V1EquipoBody} obj Optional instance to populate.
   * @return {module:model/V1EquipoBody} The populated <code>V1EquipoBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new V1EquipoBody();
      if (data.hasOwnProperty('tipo'))
        obj.tipo = ApiClient.convertToType(data['tipo'], 'String');
      if (data.hasOwnProperty('texto'))
        obj.texto = ApiClient.convertToType(data['texto'], 'String');
      if (data.hasOwnProperty('activo'))
        obj.activo = ApiClient.convertToType(data['activo'], 'Boolean');
      if (data.hasOwnProperty('imagenes'))
        obj.imagenes = ApiClient.convertToType(data['imagenes'], [V1equipoidImagenes]);
    }
    return obj;
  }
}

/**
 * @member {String} tipo
 */
V1EquipoBody.prototype.tipo = undefined;

/**
 * @member {String} texto
 */
V1EquipoBody.prototype.texto = undefined;

/**
 * @member {Boolean} activo
 */
V1EquipoBody.prototype.activo = undefined;

/**
 * @member {Array.<module:model/V1equipoidImagenes>} imagenes
 */
V1EquipoBody.prototype.imagenes = undefined;

