/*
 * API de Energy and Water
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.57
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The V1PreguntaFrecuenteBody model module.
 * @module model/V1PreguntaFrecuenteBody
 * @version 1.0.0
 */
export default class V1PreguntaFrecuenteBody {
  /**
   * Constructs a new <code>V1PreguntaFrecuenteBody</code>.
   * @alias module:model/V1PreguntaFrecuenteBody
   * @class
   * @param pregunta {String} 
   * @param respuesta {String} 
   * @param activo {Boolean} 
   */
  constructor(pregunta, respuesta, activo) {
    this.pregunta = pregunta;
    this.respuesta = respuesta;
    this.activo = activo;
  }

  /**
   * Constructs a <code>V1PreguntaFrecuenteBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/V1PreguntaFrecuenteBody} obj Optional instance to populate.
   * @return {module:model/V1PreguntaFrecuenteBody} The populated <code>V1PreguntaFrecuenteBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new V1PreguntaFrecuenteBody();
      if (data.hasOwnProperty('pregunta'))
        obj.pregunta = ApiClient.convertToType(data['pregunta'], 'String');
      if (data.hasOwnProperty('respuesta'))
        obj.respuesta = ApiClient.convertToType(data['respuesta'], 'String');
      if (data.hasOwnProperty('activo'))
        obj.activo = ApiClient.convertToType(data['activo'], 'Boolean');
    }
    return obj;
  }
}

/**
 * @member {String} pregunta
 */
V1PreguntaFrecuenteBody.prototype.pregunta = undefined;

/**
 * @member {String} respuesta
 */
V1PreguntaFrecuenteBody.prototype.respuesta = undefined;

/**
 * @member {Boolean} activo
 */
V1PreguntaFrecuenteBody.prototype.activo = undefined;

