/*
 * API de Energy and Water
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.57
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApiDeEnergyAndWater);
  }
}(this, function(expect, ApiDeEnergyAndWater) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ApiDeEnergyAndWater.DefaultApi();
  });

  describe('(package)', function() {
    describe('DefaultApi', function() {
      describe('addCategoriaServicio', function() {
        it('should call addCategoriaServicio successfully', function(done) {
          // TODO: uncomment, update parameter values for addCategoriaServicio call
          /*

          instance.addCategoriaServicio(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('addEquipo', function() {
        it('should call addEquipo successfully', function(done) {
          // TODO: uncomment, update parameter values for addEquipo call
          /*

          instance.addEquipo(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('addHistoria', function() {
        it('should call addHistoria successfully', function(done) {
          // TODO: uncomment, update parameter values for addHistoria call
          /*

          instance.addHistoria(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('addInfoContacto', function() {
        it('should call addInfoContacto successfully', function(done) {
          // TODO: uncomment, update parameter values for addInfoContacto call
          /*

          instance.addInfoContacto(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('addMantenimientoInfo', function() {
        it('should call addMantenimientoInfo successfully', function(done) {
          // TODO: uncomment, update parameter values for addMantenimientoInfo call
          /*

          instance.addMantenimientoInfo(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('createPreguntaFrecuente', function() {
        it('should call createPreguntaFrecuente successfully', function(done) {
          // TODO: uncomment, update parameter values for createPreguntaFrecuente call
          /*

          instance.createPreguntaFrecuente(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('deleteCategoriaServicioById', function() {
        it('should call deleteCategoriaServicioById successfully', function(done) {
          // TODO: uncomment, update parameter values for deleteCategoriaServicioById call
          /*

          instance.deleteCategoriaServicioById(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('deleteEquipo', function() {
        it('should call deleteEquipo successfully', function(done) {
          // TODO: uncomment, update parameter values for deleteEquipo call
          /*

          instance.deleteEquipo(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('deleteHistoria', function() {
        it('should call deleteHistoria successfully', function(done) {
          // TODO: uncomment, update parameter values for deleteHistoria call
          /*

          instance.deleteHistoria(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('deleteInfoContacto', function() {
        it('should call deleteInfoContacto successfully', function(done) {
          // TODO: uncomment, update parameter values for deleteInfoContacto call
          /*

          instance.deleteInfoContacto(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('deleteMantenimientoInfo', function() {
        it('should call deleteMantenimientoInfo successfully', function(done) {
          // TODO: uncomment, update parameter values for deleteMantenimientoInfo call
          /*

          instance.deleteMantenimientoInfo(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('deletePreguntaFrecuente', function() {
        it('should call deletePreguntaFrecuente successfully', function(done) {
          // TODO: uncomment, update parameter values for deletePreguntaFrecuente call
          /*

          instance.deletePreguntaFrecuente(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getAllCategoriasServicio', function() {
        it('should call getAllCategoriasServicio successfully', function(done) {
          // TODO: uncomment getAllCategoriasServicio call
          /*

          instance.getAllCategoriasServicio(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getAllEquipos', function() {
        it('should call getAllEquipos successfully', function(done) {
          // TODO: uncomment getAllEquipos call
          /*

          instance.getAllEquipos(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getAllHistorias', function() {
        it('should call getAllHistorias successfully', function(done) {
          // TODO: uncomment getAllHistorias call
          /*

          instance.getAllHistorias(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getAllInfoContacto', function() {
        it('should call getAllInfoContacto successfully', function(done) {
          // TODO: uncomment getAllInfoContacto call
          /*

          instance.getAllInfoContacto(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getAllMantenimientoInfo', function() {
        it('should call getAllMantenimientoInfo successfully', function(done) {
          // TODO: uncomment getAllMantenimientoInfo call
          /*

          instance.getAllMantenimientoInfo(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getAllPreguntasFrecuentes', function() {
        it('should call getAllPreguntasFrecuentes successfully', function(done) {
          // TODO: uncomment getAllPreguntasFrecuentes call
          /*

          instance.getAllPreguntasFrecuentes(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getCategoriaServicioById', function() {
        it('should call getCategoriaServicioById successfully', function(done) {
          // TODO: uncomment, update parameter values for getCategoriaServicioById call
          /*

          instance.getCategoriaServicioById(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getEquipoById', function() {
        it('should call getEquipoById successfully', function(done) {
          // TODO: uncomment, update parameter values for getEquipoById call
          /*

          instance.getEquipoById(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getHistoriaById', function() {
        it('should call getHistoriaById successfully', function(done) {
          // TODO: uncomment, update parameter values for getHistoriaById call
          /*

          instance.getHistoriaById(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getInfoContactoById', function() {
        it('should call getInfoContactoById successfully', function(done) {
          // TODO: uncomment, update parameter values for getInfoContactoById call
          /*

          instance.getInfoContactoById(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getMantenimientoInfoById', function() {
        it('should call getMantenimientoInfoById successfully', function(done) {
          // TODO: uncomment, update parameter values for getMantenimientoInfoById call
          /*

          instance.getMantenimientoInfoById(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getPreguntaFrecuenteById', function() {
        it('should call getPreguntaFrecuenteById successfully', function(done) {
          // TODO: uncomment, update parameter values for getPreguntaFrecuenteById call
          /*

          instance.getPreguntaFrecuenteById(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('partialUpdateCategoriaServicio', function() {
        it('should call partialUpdateCategoriaServicio successfully', function(done) {
          // TODO: uncomment, update parameter values for partialUpdateCategoriaServicio call
          /*

          instance.partialUpdateCategoriaServicio(body, id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('partialUpdateEquipo', function() {
        it('should call partialUpdateEquipo successfully', function(done) {
          // TODO: uncomment, update parameter values for partialUpdateEquipo call
          /*

          instance.partialUpdateEquipo(body, id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('partialUpdateHistoria', function() {
        it('should call partialUpdateHistoria successfully', function(done) {
          // TODO: uncomment, update parameter values for partialUpdateHistoria call
          /*

          instance.partialUpdateHistoria(body, id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('partialUpdateInfoContacto', function() {
        it('should call partialUpdateInfoContacto successfully', function(done) {
          // TODO: uncomment, update parameter values for partialUpdateInfoContacto call
          /*

          instance.partialUpdateInfoContacto(body, id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('partialUpdateMantenimientoInfo', function() {
        it('should call partialUpdateMantenimientoInfo successfully', function(done) {
          // TODO: uncomment, update parameter values for partialUpdateMantenimientoInfo call
          /*

          instance.partialUpdateMantenimientoInfo(body, id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('partialUpdatePreguntaFrecuente', function() {
        it('should call partialUpdatePreguntaFrecuente successfully', function(done) {
          // TODO: uncomment, update parameter values for partialUpdatePreguntaFrecuente call
          /*

          instance.partialUpdatePreguntaFrecuente(body, id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('updateHistoria', function() {
        it('should call updateHistoria successfully', function(done) {
          // TODO: uncomment, update parameter values for updateHistoria call
          /*

          instance.updateHistoria(body, id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('updateInfoContacto', function() {
        it('should call updateInfoContacto successfully', function(done) {
          // TODO: uncomment, update parameter values for updateInfoContacto call
          /*

          instance.updateInfoContacto(body, id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('updateMantenimientoInfo', function() {
        it('should call updateMantenimientoInfo successfully', function(done) {
          // TODO: uncomment, update parameter values for updateMantenimientoInfo call
          /*

          instance.updateMantenimientoInfo(body, id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('updateOrCreateCategoriaServicio', function() {
        it('should call updateOrCreateCategoriaServicio successfully', function(done) {
          // TODO: uncomment, update parameter values for updateOrCreateCategoriaServicio call
          /*

          instance.updateOrCreateCategoriaServicio(body, id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('updateOrCreateEquipo', function() {
        it('should call updateOrCreateEquipo successfully', function(done) {
          // TODO: uncomment, update parameter values for updateOrCreateEquipo call
          /*

          instance.updateOrCreateEquipo(body, id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('updatePreguntaFrecuente', function() {
        it('should call updatePreguntaFrecuente successfully', function(done) {
          // TODO: uncomment, update parameter values for updatePreguntaFrecuente call
          /*

          instance.updatePreguntaFrecuente(body, id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
